#!/usr/bin/env bash
# Download and confiure a web server

# Update package list
sudo apt-get update

# Install Nginx
sudo apt -y install nginx

# Start Nginx
sudo service nginx start

# Create a simple HTML page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Create a simple error page
echo "Ola Passito lekaae" | sudo tee /var/www/html/404.html

# Configure Nginx
printf '%s\n' "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	# Add a custom header
	add_header X-Served-By \$hostname;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
	
	error_page 404 /404.html;
	
	location = /404.html{
		internal;
	}
}" | sudo tee /etc/nginx/sites-available/default > /dev/null
 
# Reload Nginx
sudo service nginx reload
