#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
sudo apt-get install -y software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get install -y haproxy=1.8.\*
echo "
frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back
backend http_back
   balance roundrobin
   mode http
   server 225251-web-01 100.26.220.168 check
   server 225251-web-02 100.26.152.121 check" | sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy restart
