#!/usr/bin/env bash
# Update package list
sudo apt-get update

# Install haproxy
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y update
sudo apt-get -y install haproxy=2.8.\*

# start the service
sudo service haproxy start

#Configure the config file
printf '%s\n' "frontend web
	bind *:80
	default_backend myservers

backend myservers
	balance roundrobin
	server 225451-web-01 100.26.220.168:80
	server 225451-web-02 100.26.152.121:80
" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Reload the server
sudo service haproxy reload
