#!/usr/bin/env bash
#This script configures a server:
# *** locahost resolves to 127.0.0.2
# *** facebook.com resolves to 8.8.8.8

cp /stc/hosts ~/hosts.new
echo "127.0.0.2 	losthost" > ~/hosts.new
echo "8.8.8.8		facebook" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
